<template>
  <div
    class="
      bg-graybackground
      dark:bg-secondary
      flex flex-col
      items-left
      max-w-4xl
      w-11/12
      lg:4/5 lg:px-20
      px-4
      py-16
      my-20
      rounded-3xl
      drop-shadow-2xl
    "
  >
    <p
      class="
        text-primary
        dark:text-white
        text-left text-[36px]
        font-semibold
        mb-5
      "
    >
      Fiat On-Ramp
    </p>
    <p
      class="text-primary dark:text-white text-left text-[20px] font-bold my-6"
    >
      Select Currency And Payment Method
    </p>
    <p
      class="
        text-primary
        dark:text-white
        text-[18px]
        font-semibold
        text-left
        my-3
      "
    >
      Currency
    </p>
    <div class="flex justify-between mb-20">
      <div
        class="
          bg-inputbackground
          dark:bg-primary
          flex
          justify-center
          items-center
          mr-3
          w-32
          h-16
          rounded-xl
        "
      >
        <img src="/src/assets/images/eur.png" alt="Image" class="eth" />
        <p class="text-white text-[14px] ml-4">ETH</p>
      </div>
      <input
        type="text"
        value="0"
        class="
          bg-inputbackground
          dark:bg-primary
          rounded-xl
          h-16
          lg:w-full
          text-white
          pl-5
        "
      />
    </div>
    <p
      class="text-primary dark:text-white text-left text-[20px] font-bold my-6"
    >
      Purchase Details
    </p>
    <p
      class="
        text-primary
        dark:text-white
        text-[18px]
        font-semibold
        text-left
        my-3
      "
    >
      Amount Estimated
    </p>
    <div class="flex justify-between">
      <div
        class="
          bg-inputbackground
          dark:bg-primary
          flex
          justify-center
          items-center
          mr-3
          w-32
          h-16
          rounded-xl
        "
      >
        <img src="/src/assets/images/usdc.png" alt="Image" class="eth" />
        <p class="text-white text-[14px] ml-4">USDC</p>
      </div>
      <input
        type="text"
        value="0"
        class="
          bg-inputbackground
          dark:bg-primary
          rounded-xl
          h-16
          lg:w-full
          text-white
          pl-5
        "
      />
    </div>
    <div class="lg:flex items-center justify-center m-auto lg:mr-40 mt-20">
      <p
        class="
          text-primary
          dark:text-white
          text-[15px]
          w-40
          font-semibold
          uppercase
          mr-4
          text-right
        "
      >
        Exchange&nbsp;Rate
      </p>
      <p
        class="
          bg-inputbackground
          dark:bg-primary
          flex
          items-center
          pl-4
          w-48
          h-8
          rounded-md
          font-semibold
          items-center
          text-white
          mt-4
          lg:mt-10
        "
      >
        1&nbsp;USDC&nbsp;=&nbsp;1,023&nbsp;EUR
      </p>
    </div>
    <div class="lg:flex items-center justify-center m-auto lg:mr-40">
      <p
        class="
          text-primary
          dark:text-white
          text-[15px]
          w-40
          font-semibold
          uppercase
          mr-4
          mt-10
          text-right
        "
      >
        You&nbsp;Will&nbsp;Get
      </p>
      <p
        class="
          bg-inputbackground
          dark:bg-primary
          flex
          items-center
          pl-16
          w-48
          h-8
          rounded-md
          font-semibold
          items-center
          text-white
          mt-4
          lg:mt-10
        "
      >
        234&nbsp;USDC
      </p>
    </div>
    <button
      class="
        bg-primary
        border-solid border border-pinks
        rounded-3xl
        w-48
        h-12
        mt-20
        m-auto
        text-lg text-white
        mt-20
      "
    >
      Connect Wallet
    </button>
  </div>
</template>
